# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ATT_Monthly_Report(object):
    def setupUi(self, ATT_Monthly_Report):
        ATT_Monthly_Report.setObjectName("ATT_Monthly_Report")
        ATT_Monthly_Report.resize(394, 307)
        self.traffic = QtWidgets.QTabWidget(ATT_Monthly_Report)
        self.traffic.setGeometry(QtCore.QRect(0, 0, 401, 311))
        self.traffic.setObjectName("traffic")
        self.UMTS = QtWidgets.QWidget()
        self.UMTS.setObjectName("UMTS")
        self.umts_counters_1 = QtWidgets.QToolButton(self.UMTS)
        self.umts_counters_1.setGeometry(QtCore.QRect(10, 50, 181, 81))
        self.umts_counters_1.setObjectName("UMTS_Counters_1")
        self.umts_counters_2 = QtWidgets.QToolButton(self.UMTS)
        self.umts_counters_2.setGeometry(QtCore.QRect(200, 50, 181, 81))
        self.umts_counters_2.setObjectName("UMTS_Counters_2")
        self.runUMTS = QtWidgets.QPushButton(self.UMTS)
        self.runUMTS.setGeometry(QtCore.QRect(110, 180, 161, 51))
        self.runUMTS.setObjectName("runUMTS_2")
        self.traffic.addTab(self.UMTS, "")
        self.LTE = QtWidgets.QWidget()
        self.LTE.setObjectName("LTE")
        self.runLTE = QtWidgets.QPushButton(self.LTE)
        self.runLTE.setGeometry(QtCore.QRect(110, 200, 181, 61))
        self.runLTE.setObjectName("ruLTE")
        self.lte_counters_1 = QtWidgets.QToolButton(self.LTE)
        self.lte_counters_1.setGeometry(QtCore.QRect(10, 10, 181, 81))
        self.lte_counters_1.setObjectName("lte_counters_1")
        self.lte_counters_2 = QtWidgets.QToolButton(self.LTE)
        self.lte_counters_2.setGeometry(QtCore.QRect(200, 10, 181, 81))
        self.lte_counters_2.setObjectName("lte_counters_2")
        self.lte_counters_mocn = QtWidgets.QToolButton(self.LTE)
        self.lte_counters_mocn.setGeometry(QtCore.QRect(10, 100, 181, 81))
        self.lte_counters_mocn.setObjectName("lte_counters_mocn")
        self.traffic.addTab(self.LTE, "")

        self.retranslateUi(ATT_Monthly_Report)
        self.traffic.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ATT_Monthly_Report)

    def retranslateUi(self, ATT_Monthly_Report):
        _translate = QtCore.QCoreApplication.translate
        ATT_Monthly_Report.setWindowTitle(_translate("ATT_Monthly_Report", "ATT Monthly Report Tool"))
        self.umts_counters_1.setText(_translate("ATT_Monthly_Report", "UMTS Counters 1"))
        self.umts_counters_2.setText(_translate("ATT_Monthly_Report", "UMTS Counters 2"))
        self.runUMTS.setText(_translate("ATT_Monthly_Report", "RUN"))
        self.traffic.setTabText(self.traffic.indexOf(self.UMTS), _translate("ATT_Monthly_Report", "UMTS"))
        self.runLTE.setText(_translate("ATT_Monthly_Report", "RUN"))
        self.lte_counters_1.setText(_translate("ATT_Monthly_Report", "LTE Counters 1"))
        self.lte_counters_2.setText(_translate("ATT_Monthly_Report", "LTE Counters 2"))
        self.lte_counters_mocn.setText(_translate("ATT_Monthly_Report", "LTE MOCN"))
        self.traffic.setTabText(self.traffic.indexOf(self.LTE), _translate("ATT_Monthly_Report", "LTE"))
